In [4]:
a = list('0000')
N = 4
def enumerate(k):
#     print(k)
    if k == N:
        #process()
        print(a)
        return
    a[k] = '1'
    enumerate(k + 1)
    a[k] = '0'
    enumerate(k + 1)
    
enumerate(0)
    

['1', '1', '1', '1']
['1', '1', '1', '0']
['1', '1', '0', '1']
['1', '1', '0', '0']
['1', '0', '1', '1']
['1', '0', '1', '0']
['1', '0', '0', '1']
['1', '0', '0', '0']
['0', '1', '1', '1']
['0', '1', '1', '0']
['0', '1', '0', '1']
['0', '1', '0', '0']
['0', '0', '1', '1']
['0', '0', '1', '0']
['0', '0', '0', '1']
['0', '0', '0', '0']


## N queens Problem

In [ ]:
# a = [1, 2, 3, 4, 5, 6, 7]
# a = [1, 2, 3, 4, 0]
a = [1,2,3,4,5, 6, 7, 8, 9, 10, 11]
def swap(a, i, k):
    c, d = a[i], a[k]
    a[k] = c
    a[i] = d
N = len(a)
count = 0
def enumeratePermutate(k):
    global count
    def canBacktrack():
        for i in range(0, k):
            '''Think on this like a growing pyramid and
            anything that is on the diagonal (k - i) has to be eliminated'''
            if (abs(a[i] - a[k]) == (k - i)):
                return True
        return False
    if k == N:
        (count) = (count) + 1
        return
    for i in range(k, N):
        swap(a, i, k)
        if (canBacktrack() is not True):
            enumeratePermutate(k + 1)
        swap(a, i, k)
        
enumeratePermutate(0)
print(count)


In [133]:
'''counting N-digit base-R numbers,
    with currying'''
import numpy as np
# N = 2
# R = 4
# a = [0] * N
def countDigits(N):
    k = 0
    a = [0] * N
    def enumerateDigits(k, R):
        global count
        if k == N:
            print(a)
            return
        for i in range(R):
            a[k] = i
            enumerateDigits(k + 1, R)
    countToBase = lambda R: enumerateDigits(0, R)
    return countToBase
        
countTwoDigitsWithBase = countDigits(2)
countThreeDigitsWithBase = countDigits(3)
# countTwoDigitsWithBase(3)
# print('')
# countTwoDigitsWithBase(4)
print('')
# countThreeDigitsWithBase(3)
countDigits(3)(2)



[0, 0, 0]
[0, 0, 1]
[0, 1, 0]
[0, 1, 1]
[1, 0, 0]
[1, 0, 1]
[1, 1, 0]
[1, 1, 1]


In [244]:
'''sudoku solver'''
# board = np.zeros((9,9))
def resetBoard():
    board = np.zeros((9,9))
    board[0][0] = 7
    board[0][2] = 8
    board[0][6] = 3
    board[1][3] = 2
    board[1][5] = 1
    board[2][0] = 5
    board[3][1] = 4
    board[3][7] = 2
    board[3][8] = 6
    board[4][0] = 3
    board[4][4] = 8
    board[5][3] = 1
    board[5][7] = 9
    board[6][1] = 9
    board[6][3] = 6
    board[6][8] = 4
    board[7][4] = 7
    board[7][6] = 5
    return board

print(resetBoard())

[[ 7.  0.  8.  0.  0.  0.  3.  0.  0.]
 [ 0.  0.  0.  2.  0.  1.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.  0.  2.  6.]
 [ 3.  0.  0.  0.  8.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  9.  0.]
 [ 0.  9.  0.  6.  0.  0.  0.  0.  4.]
 [ 0.  0.  0.  0.  7.  0.  5.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [341]:
import math
def boxNumber(k):
    section = math.floor((k)/ 27)
    boxWithinSection = math.ceil(((k + 10e-7) % 9)/ 3)
    return section * 3 + boxWithinSection
StartLocationOfBox = lambda box: math.floor(box/3) * 27 + (box % 3) * 3
def canBackTrack(a, k):
    if a[k] == 0:
        return True
    #Find if the number exists in the same row
    row = math.floor(k / 9)
    for i in range(9):
        if k == (row * 9 + i):
            continue
        if a[k] == a[row * 9 + i] and a[k] != 0:
            return True
    #Find if the number exists in the same column
    col = k % 9
    for i in range(9):
        if k == (i * 9 + col):
            continue
        if a[k] == a[i * 9 + col] and a[k] != 0:
            return True
        
    #Find is the number exists in within the same box
    box = boxNumber(k)
    boxStart = StartLocationOfBox(box - 1)
    for i in range(boxStart, boxStart + 3):
        for j in range(3):
            if k == i + j * 9:
                continue
            if a[k] == a[i + j * 9] and a[k] != 0:
                return True
    return False

# print(boxNumber(80))
# print(StartLocationOfBox(0))

In [ ]:
board = resetBoard()
a = np.reshape(board, -1)
idx = np.where(a > 0)[0]
def enumerateSudoku(k):
    if k == 81:
        print(np.reshape(a,(9,9)))
        return
    for i in range(1, 10):
        if k in idx:
            enumerateSudoku(k + 1)
            break
        else:
            a[k] = i
            if (canBackTrack(a, k) is False):
                enumerateSudoku(k + 1)
            a[k] = 0
enumerateSudoku(0)

In [402]:
'''Enumerate binary digits'''
import copy
N = 3
a = [0] * N  
def enumerateBinary(k):
    if k == N:
        print(a)
        return
    enumerateBinary(k + 1)
    a[k] = 1 - a[k]
    enumerateBinary(k + 1)

enumerateBinary(0)

[0, 0, 0]
[0, 0, 1]
[0, 1, 1]
[0, 1, 0]
[1, 1, 0]
[1, 1, 1]
[1, 0, 1]
[1, 0, 0]


In [420]:
'''load balance jobs based on finish times'''
import sys
jobs = [1.41, 1.73, 2.0, 2.23, 1.2, 6.0]
N = len(jobs)
a = [0] * N
bestAllocation = [0] * N
bestSpan = sys.maxsize
def calcSpan(a, id):
    span = 0
    for i in range(N):
        if a[i] == id:
            span += jobs[i]            
    return span

makeSpan = lambda a: abs(calcSpan(a, 0) - calcSpan(a, 1))

def canBacktrackJobs(a) -> bool:
    currentSpan =  makeSpan(a)
    if currentSpan > bestSpan:
        return True
    return False
    
def enumerateJobs(k):
    global bestSpan
    global bestAllocation
    if k == N:
        totalSpan = makeSpan(a)
        if totalSpan < bestSpan:
            bestSpan = totalSpan
            bestAllocation = copy.deepcopy(a)
        return
    if canBacktrackJobs(a):
        return
    enumerateJobs(k + 1)
    a[k] = 1 - a[k]
    enumerateJobs(k + 1)
    
enumerateJobs(0)
print('Best allocation:', bestAllocation)

Best allocation: [0, 0, 0, 0, 1, 1]
